## Roska File Descriptor — context/tui-config.tsx
file: context/tui-config.tsx
lines: 9
layer: logic
imports:
- sym: '@/config/tui.TuiConfig'
- sym: ./helper.createSimpleContext
data:
- name: '{ use: useTuiConfig, provider: TuiConfigProvider }'
  type: any
  val: |-
    createSimpleContext({
      name: "TuiConfig",
      init: (props: { config: TuiConfig.Info }) => {
        return props.config
      },...
exports:
- name: '{ use: useTuiConfig, provider: TuiConfigProvider }'
  kind: data
