## Roska File Descriptor — config/diffEditor.ts
file: config/diffEditor.ts
lines: 40
layer: logic
purpose: '--------------------------------------------------------------------------------------------- Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT License. See License.txt in the project root for license information. --------------------------------------------------------------------------------------------'
imports:
- sym: ./editorOptions.js.ValidDiffEditorBaseOptions
data:
- name: diffEditorDefaultOptions
  type: object
  val: "{\n\tenableSplitViewResizing: true,\n\tsplitViewDefaultRatio: 0.5,\n\trenderSideBySide: true,\n\trenderMarginRevertIcon: true,\n\t..."
exports:
- name: diffEditorDefaultOptions
  kind: data
