"""
Moko Agent — Code Intelligence Agent for Roska Descriptors.

Inspired by Cline's architecture: Supervisor → Agents → PromptRegistry → VectorStore.
Provides semantic search, architecture analysis, and cross-project comparison
over 31K+ YAML descriptors generated by the Roska compiler (lyzed-ts).
"""

from pathlib import Path

# Paths relative to project root
ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = ROOT / "src"
OUT_DIR = ROOT / "out"
REGISTRY_PATH = ROOT / "projects.json"
VECTORDB_PATH = OUT_DIR / ".vectordb"

__version__ = "0.1.0"
