"""
Moko Agent — Code Intelligence Agent for Roska Descriptors.

Inspired by Cline's architecture: Supervisor → Agents → PromptRegistry → VectorStore.
Provides semantic search, architecture analysis, and cross-project comparison
over 31K+ YAML descriptors generated by the Roska compiler.
"""

import logging
from pathlib import Path

# Paths relative to project root
ROOT = Path(__file__).resolve().parent.parent.parent
SRC_DIR = ROOT / "src"
OUT_DIR = ROOT / "out"
REGISTRY_PATH = ROOT / "projects.json"
VECTORDB_PATH = OUT_DIR / ".vectordb"
PROJECTS_DIR = ROOT / "projects"
PLANS_DIR = OUT_DIR / ".plans"

__version__ = "0.3.0"

# Centralized logger — all subsystems should use `from agent import log`
log = logging.getLogger("moko")
if not log.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter(
        "  [%(name)s.%(module)s] %(message)s"
    ))
    log.addHandler(_handler)
    log.setLevel(logging.WARNING)


def set_verbose(enabled: bool = True) -> None:
    """Enable/disable verbose logging for all moko subsystems."""
    log.setLevel(logging.DEBUG if enabled else logging.WARNING)
