## Roska File Descriptor — config/client.py
file: config/client.py
lines: 511
layer: logic
imports:
- sym: subprocess
- sym: traceback
- sym: github
- sym: yaml
- sym: github.Repository.Repository
- sym: loguru.logger
- sym: pydantic.BaseModel
- sym: sweepai.core.entities.EmptyRepository
- sym: sweepai.utils.event_logger.posthog
- sym: sweepai.utils.file_utils.encode_file_with_fallback_encodings
- sym: sweepai.utils.file_utils.read_file_with_fallback_encodings
data:
- name: GITHUB_APP_CLIENT_ID
  type: Any
  val: os.environ.get("GITHUB_APP_CLIENT_ID", "Iv1.91fd31586a926a9f")
- name: RESTART_SWEEP_BUTTON
  type: str
  val: '"↻ Restart Sweep"'
- name: SWEEP_GOOD_FEEDBACK
  type: str
  val: '"👍 Sweep Did Well"'
- name: SWEEP_BAD_FEEDBACK
  type: str
  val: '"👎 Sweep Needs Improvement"'
- name: RESET_FILE
  type: str
  val: '"Rollback changes to "'
- name: REVERT_CHANGED_FILES_TITLE
  type: str
  val: '"## Rollback Files For Sweep"'
- name: RULES_TITLE
  type: tuple
  val: |-
    (
        "## Apply [Sweep Rules](https://docs.sweep.dev/usage/config#rules) to your PR?"
    )
- name: RULES_LABEL
  type: str
  val: '"**Apply:** "'
- name: DEFAULT_RULES
  type: list
  val: |-
    [
        "All new business logic should have corresponding unit tests.",
        "Refactor large functions to be more modular."...
- name: DEFAULT_RULES_STRING
  type: str
  val: |-
    """\
      - "All new business logic should have corresponding unit tests."
      - "Refactor large functions to be more modular...
types:
- name: SweepConfig
  kind: model
  bases:
  - BaseModel
  fields:
  - name: include_dirs
    type: Any
    default: list[str]
  - name: exclude_dirs
    type: Any
    default: list[str]
  - name: exclude_path_dirs
    type: Any
    default: list[str]
  - name: exclude_substrings_aggressive
    type: Any
    default: list[str]
  - name: include_exts
    type: Any
    default: list[str]
  - name: exclude_exts
    type: Any
    default: list[str]
  - name: excluded_languages
    type: Any
    default: list[str]
  - name: truncation_cutoff
    type: Any
    default: int
  - name: max_file_limit
    type: Any
    default: int
  - name: max_github_comment_body_length
    type: Any
    default: int
  - name: allowed_image_types
    type: Any
    default: list[str]
  methods:
  - name: to_yaml
    sig: to_yaml(self) -> str
    lines:
    - 150
    - 151
    detail:
      calls:
      - self.dict
      - yaml.safe_dump
  - name: from_yaml
    sig: 'from_yaml(cls, yaml_str: str) -> "SweepConfig"'
    decorators:
    - classmethod
    lines:
    - 154
    - 156
    detail:
      calls:
      - cls.parse_obj
      - yaml.safe_load
  - name: get_branch
    sig: 'get_branch(repo: Repository, override_branch: str | None = None) -> str'
    decorators:
    - staticmethod
    - lru_cache()
    lines:
    - 160
    - 215
    detail:
      calls:
      - '"/".join'
      - Exception
      - branch_name.split
      - branch_name.split(" ")[0].split
      - branch_name_combos.append
      - contents.decoded_content.decode
      - len
      - logger.exception
      - range
      - repo.create_git_ref
      - repo.get_branch
      - repo.get_contents
      - traceback.format_exc
      - yaml.safe_load
  - name: get_config
    sig: 'get_config(repo: Repository)'
    decorators:
    - staticmethod
    lines:
    - 218
    - 227
    detail:
      calls:
      - EmptyRepository
      - SweepConfig
      - contents.decoded_content.decode
      - logger.warning
      - repo.get_contents
      - str
      - yaml.safe_load
  - name: get_draft
    sig: 'get_draft(repo: Repository)'
    decorators:
    - staticmethod
    lines:
    - 230
    - 237
    detail:
      calls:
      - config.get
      - contents.decoded_content.decode
      - logger.warning
      - repo.get_contents
      - yaml.safe_load
  - name: is_file_excluded
    sig: 'is_file_excluded(self, file_path: str) -> bool'
    lines:
    - 240
    - 253
    detail:
      calls:
      - enumerate
      - file_path.split
      - len
      - part.endswith
  - name: is_file_excluded_aggressive
    sig: 'is_file_excluded_aggressive(self, dir: str, file_path: str) -> bool'
    lines:
    - 256
    - 305
    detail:
      calls:
      - data.split
      - f.read
      - file_path.split
      - iter
      - len
      - logger.warning
      - open
      - os.path.exists
      - os.path.join
      - os.stat
      - read_file_with_fallback_encodings
      - self.is_file_auto_generated
  - name: is_file_suitable
    sig: 'is_file_suitable(self, file_contents: str) -> tuple[bool, str]'
    lines:
    - 310
    - 329
    detail:
      calls:
      - encode_file_with_fallback_encodings
      - file_contents.split
      - len
      - logger.warning
  - name: is_file_bad
    sig: 'is_file_bad(self, file_name: str, repo_dir: str) -> tuple[bool, str]'
    lines:
    - 331
    - 369
    detail:
      calls:
      - '" ".join'
      - bool
      - json.loads
      - logger.error
      - posthog.capture
      - re.search
      - str
      - subprocess.run
  lines:
  - 21
  - 369
functions:
- name: get_gha_enabled
  sig: 'get_gha_enabled(repo: Repository) -> bool'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 374
  - 391
  detail:
    calls:
    - contents.decoded_content.decode
    - logger.info
    - repo.get_contents
    - yaml.safe_load
    - yaml.safe_load(contents.decoded_content.decode("utf-8")).get
- name: get_config_key_value
  sig: 'get_config_key_value(repo: Repository, key_name: str) -> bool'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 394
  - 411
  detail:
    calls:
    - contents.decoded_content.decode
    - logger.info
    - repo.get_contents
    - yaml.safe_load
    - yaml.safe_load(contents.decoded_content.decode("utf-8")).get
- name: get_description
  sig: 'get_description(repo: Repository) -> dict'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 414
  - 423
  detail:
    calls:
    - '"\n * ".join'
    - contents.decoded_content.decode
    - repo.get_contents
    - sweep_yaml.get
    - yaml.safe_load
- name: get_sandbox_config
  sig: 'get_sandbox_config(repo: Repository)'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 427
  - 435
  detail:
    calls:
    - contents.decoded_content.decode
    - repo.get_contents
    - yaml.safe_load
    - yaml.safe_load(contents.decoded_content.decode("utf-8")).get
- name: get_branch_name_config
  sig: 'get_branch_name_config(repo: Repository)'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 439
  - 447
  detail:
    calls:
    - contents.decoded_content.decode
    - repo.get_contents
    - yaml.safe_load
    - yaml.safe_load(contents.decoded_content.decode("utf-8")).get
- name: get_documentation_dict
  sig: 'get_documentation_dict(repo: Repository)'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 451
  - 460
  detail:
    calls:
    - repo.get_contents
    - repo.get_contents("sweep.yaml").decoded_content.decode
    - sweep_yaml.get
    - yaml.safe_load
- name: get_blocked_dirs
  sig: 'get_blocked_dirs(repo: Repository)'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 464
  - 473
  detail:
    calls:
    - repo.get_contents
    - repo.get_contents("sweep.yaml").decoded_content.decode
    - sweep_yaml.get
    - yaml.safe_load
- name: get_rules
  sig: 'get_rules(repo: Repository)'
  decorators:
  - lru_cache(maxsize=None)
  lines:
  - 476
  - 485
  detail:
    calls:
    - repo.get_contents
    - repo.get_contents("sweep.yaml").decoded_content.decode
    - sweep_yaml.get
    - yaml.safe_load
exports:
- name: SweepConfig
  kind: type
- name: get_gha_enabled
  kind: func
- name: get_config_key_value
  kind: func
- name: get_description
  kind: func
- name: get_sandbox_config
  kind: func
- name: get_branch_name_config
  kind: func
- name: get_documentation_dict
  kind: func
- name: get_blocked_dirs
  kind: func
- name: get_rules
  kind: func
- name: GITHUB_APP_CLIENT_ID
  kind: data
- name: RESTART_SWEEP_BUTTON
  kind: data
- name: SWEEP_GOOD_FEEDBACK
  kind: data
- name: SWEEP_BAD_FEEDBACK
  kind: data
- name: RESET_FILE
  kind: data
- name: REVERT_CHANGED_FILES_TITLE
  kind: data
- name: RULES_TITLE
  kind: data
- name: RULES_LABEL
  kind: data
- name: DEFAULT_RULES
  kind: data
- name: DEFAULT_RULES_STRING
  kind: data
