"""
SharedTypeDetector — detect types referenced by 2+ classes without a file, auto-generate types.ts.

When the LLM generates code that imports shared types (e.g., AddressingMode, IODevice)
from files that don't exist, this detector:
1. Identifies which types are referenced by multiple files but have no source
2. Collects context about each type from its usage sites
3. Generates a minimal types.ts that satisfies all import requirements
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from .graph import ProjectGraph, ExportedSymbol


@dataclass
class OrphanType:
    """A type referenced in imports but not exported by any file."""
    name: str
    referenced_by: list[str] = field(default_factory=list)  # files that import it
    import_paths: list[str] = field(default_factory=list)    # paths used to import it
    usage_context: list[str] = field(default_factory=list)   # usage lines for context
    inferred_kind: str = "interface"  # best guess: interface, enum, type


@dataclass
class SharedTypesPlan:
    """Plan for generating a shared types file."""
    orphans: list[OrphanType]
    target_file: str        # e.g., "cpu/types.ts"
    module: str             # e.g., "cpu"


class SharedTypeDetector:
    """Detect and plan generation for shared types that have no source file."""

    def __init__(self, graph: ProjectGraph):
        self.graph = graph

    def detect(self) -> list[SharedTypesPlan]:
        """Detect orphan types across all modules. Returns plans per module."""
        # 1. Collect all import references that don't resolve
        orphans_by_module: dict[str, dict[str, OrphanType]] = {}

        for file_path, node in self.graph.files.items():
            module = self.graph._module_from_path(file_path)

            for imp in node.imports:
                if not imp.is_relative:
                    continue

                result = self.graph.resolve_import(file_path, imp.path)
                if result.resolved:
                    # Check for specific symbol mismatches
                    if result.symbols:
                        for name in imp.names:
                            clean = name.split(" as ")[-1].strip()
                            if clean and clean not in result.symbols:
                                if module not in orphans_by_module:
                                    orphans_by_module[module] = {}
                                if clean not in orphans_by_module[module]:
                                    orphans_by_module[module][clean] = OrphanType(name=clean)
                                ot = orphans_by_module[module][clean]
                                ot.referenced_by.append(file_path)
                                ot.import_paths.append(imp.path)
                else:
                    # Whole file doesn't resolve — all its names are orphans
                    for name in imp.names:
                        clean = name.split(" as ")[-1].strip()
                        if not clean:
                            continue
                        if module not in orphans_by_module:
                            orphans_by_module[module] = {}
                        if clean not in orphans_by_module[module]:
                            orphans_by_module[module][clean] = OrphanType(name=clean)
                        ot = orphans_by_module[module][clean]
                        ot.referenced_by.append(file_path)
                        ot.import_paths.append(imp.path)

        # 2. Enrich with usage context and infer kind
        for module, orphans in orphans_by_module.items():
            for name, ot in orphans.items():
                self._infer_kind(ot)
                self._collect_usage_context(ot)

        # 3. Build plans — only for types referenced by 2+ files
        plans = []
        for module, orphans in orphans_by_module.items():
            shared = [ot for ot in orphans.values() if len(set(ot.referenced_by)) >= 2]
            if shared:
                plans.append(SharedTypesPlan(
                    orphans=shared,
                    target_file=f"{module}/types.ts",
                    module=module,
                ))

        return plans

    def detect_for_module(self, module: str) -> Optional[SharedTypesPlan]:
        """Detect orphan types for a specific module."""
        plans = self.detect()
        for plan in plans:
            if plan.module == module:
                return plan
        return None

    def generate_stub(self, plan: SharedTypesPlan) -> str:
        """Generate a minimal types.ts stub that satisfies import requirements.

        The stub contains placeholder types that compile. The LLM can later
        fill in the real implementation.
        """
        lines = [
            "/**",
            f" * Shared types for {plan.module} module.",
            " * Auto-generated by SharedTypeDetector — fill in real implementations.",
            " */",
            "",
        ]

        for orphan in sorted(plan.orphans, key=lambda o: o.name):
            if orphan.inferred_kind == "enum":
                lines.append(f"export enum {orphan.name} {{")
                # Use usage context to populate enum values if possible
                values = self._extract_enum_hints(orphan)
                if values:
                    for val in values:
                        lines.append(f"  {val},")
                else:
                    lines.append("  // TODO: add enum values")
                lines.append("}")
            elif orphan.inferred_kind == "type":
                lines.append(f"export type {orphan.name} = unknown; // TODO: define type")
            else:
                lines.append(f"export interface {orphan.name} {{")
                # Use usage context to infer fields
                fields = self._extract_field_hints(orphan)
                if fields:
                    for fname, ftype in fields:
                        lines.append(f"  {fname}: {ftype};")
                else:
                    lines.append("  // TODO: add fields")
                lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def _infer_kind(self, orphan: OrphanType) -> None:
        """Infer whether the orphan is an enum, interface, or type alias."""
        name = orphan.name

        # Heuristic: names ending in Mode, Type, Flag, Status → likely enum
        enum_hints = ("Mode", "Flag", "Status", "Kind", "State", "Direction", "Group")
        if any(name.endswith(h) for h in enum_hints):
            orphan.inferred_kind = "enum"
            return

        # Check usage context for enum-like patterns: OrphanName.VALUE
        for ctx in orphan.usage_context:
            if re.search(rf"{name}\.\w+", ctx):
                orphan.inferred_kind = "enum"
                return

        # Names ending in Config, Options, Props, Descriptor → interface
        iface_hints = ("Config", "Options", "Props", "Descriptor", "Info", "Data", "Params")
        if any(name.endswith(h) for h in iface_hints):
            orphan.inferred_kind = "interface"
            return

        orphan.inferred_kind = "interface"

    def _collect_usage_context(self, orphan: OrphanType) -> None:
        """Read files that reference this type and extract usage lines."""
        for file_path in set(orphan.referenced_by):
            full_path = self.graph.src_dir / file_path
            try:
                code = full_path.read_text(encoding="utf-8", errors="replace")
            except (OSError, IOError):
                continue

            for line in code.splitlines():
                if orphan.name in line and "import" not in line.lower():
                    orphan.usage_context.append(line.strip())
                    if len(orphan.usage_context) > 20:
                        return

    def _extract_enum_hints(self, orphan: OrphanType) -> list[str]:
        """Try to extract enum value names from usage context."""
        values = set()
        pattern = re.compile(rf"{orphan.name}\.(\w+)")
        for ctx in orphan.usage_context:
            for m in pattern.finditer(ctx):
                val = m.group(1)
                if val[0].isupper() or val.isupper():
                    values.add(val)
        return sorted(values)

    def _extract_field_hints(self, orphan: OrphanType) -> list[tuple[str, str]]:
        """Try to extract interface fields from usage context (e.g., obj.field patterns)."""
        fields = {}
        # Pattern: variable.fieldName
        pattern = re.compile(r"\w+\.(\w+)")
        for ctx in orphan.usage_context:
            for m in pattern.finditer(ctx):
                field_name = m.group(1)
                # Skip common non-field patterns
                if field_name in ("length", "toString", "valueOf", "push", "map",
                                  "filter", "forEach", "prototype", "constructor"):
                    continue
                if field_name not in fields:
                    fields[field_name] = "unknown"
        return [(k, v) for k, v in sorted(fields.items())][:10]
