"""
Duel — Claude Code vs Ava Agent head-to-head comparison.

ava duel -t nova -r playcanvas -m math --types Vec3 Mat4

Runs the same type through two pipelines:
  A) Ava Agent: blueprint → emission → translator (with references)
  B) Claude Raw: direct LLM prompt (same spec, no Ava pipeline)

Then benchmarks both outputs and shows a comparison table.

This tests whether the Ava pipeline (blueprints, emission index,
discussions, density analysis) actually adds value vs raw prompting.
"""
from __future__ import annotations

import hashlib
import time
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from ..llm.providers import LLMProvider, LLMMessage
from .. import OUT_DIR


@dataclass
class DuelResult:
    """Result of one type generated by one agent."""
    agent: str            # "ava" or "claude"
    type_name: str        # "Vec3"
    module: str           # "math"
    code: str = ""
    loc: int = 0
    method_count: int = 0
    density: float = 0.0
    tsc_errors: int = -1
    tokens_used: int = 0
    elapsed_s: float = 0.0
    refs_used: int = 0
    code_hash: str = ""


@dataclass
class DuelRound:
    """One type, two agents."""
    type_name: str
    module: str
    ava: Optional[DuelResult] = None
    claude: Optional[DuelResult] = None


@dataclass
class DuelReport:
    """Full duel: multiple types, two agents each."""
    target: str
    references: list[str]
    rounds: list[DuelRound] = field(default_factory=list)
    total_tokens: int = 0
    elapsed_s: float = 0.0


class DuelRunner:
    """Run Claude vs Ava head-to-head on the same types."""

    def __init__(self, config: dict = None):
        config = config or {}
        self.llm = LLMProvider(
            provider=config.get("provider", "groq"),
            model=config.get("model"),
        )
        self.verbose = config.get("verbose", False)
        self.out_dir = OUT_DIR
        self.projects_dir = Path("projects")
        self.config = config

        from .guardrails import RunGuard, RunLimits
        self.guard = config.get("_guard") or RunGuard(RunLimits.from_config(config))

    def _log(self, msg: str):
        if self.verbose:
            print(f"  [duel] {msg}")

    def run(self, target: str, references: list[str],
            module: str, types: list[str],
            goal: str = "") -> DuelReport:
        """Run the duel: each type through Ava and Claude pipelines."""
        t0 = time.time()
        report = DuelReport(target=target, references=references)

        project_dir = self.projects_dir / target
        project_dir.mkdir(parents=True, exist_ok=True)

        # Setup: build blueprint + emission index (shared by Ava)
        self._log("building emission index...")
        from .emission import EmissionIndex
        emission = EmissionIndex(self.out_dir)
        emission.build(references)
        self._log(f"indexed {emission.total_types} types from {emission.total_descriptors} descriptors")

        # Load or create module blueprint
        self._log(f"loading blueprint for module '{module}'...")
        module_bp = self._get_or_create_blueprint(
            target, references, module, types, goal, emission
        )

        if not module_bp:
            print("Failed to create blueprint. Aborting.")
            return report

        # Run each type through both agents
        for type_name in types:
            self.guard.check_time()

            type_bp = None
            for t in module_bp.types:
                if t.name == type_name:
                    type_bp = t
                    break

            if not type_bp:
                self._log(f"  skipping {type_name}: not in blueprint")
                continue

            round_ = DuelRound(type_name=type_name, module=module)

            print(f"\n{'═' * 70}")
            print(f"  ROUND: {type_name}")
            print(f"{'═' * 70}")

            # Agent A: Ava pipeline
            print(f"\n  ── AVA AGENT ──")
            round_.ava = self._run_ava(
                type_bp, module_bp, project_dir, emission
            )
            report.total_tokens += round_.ava.tokens_used

            # Agent B: Claude raw
            print(f"\n  ── CLAUDE RAW ──")
            round_.claude = self._run_claude_raw(
                type_name, module, module_bp, project_dir, references, goal
            )
            report.total_tokens += round_.claude.tokens_used

            report.rounds.append(round_)

            # Print round comparison
            self._print_round(round_)

        report.elapsed_s = time.time() - t0
        self._print_final_report(report)
        self._save_results(target, report)
        return report

    # ── Agent A: Ava Pipeline ───────────────────────────────

    def _run_ava(self, type_bp, module_bp, project_dir: Path,
                 emission) -> DuelResult:
        """Run type through full Ava pipeline (translator + emission)."""
        from .translator import BlueprintTranslator

        t0 = time.time()
        result = DuelResult(
            agent="ava", type_name=type_bp.name, module=module_bp.name
        )

        # Setup translator with emission
        translator = BlueprintTranslator(
            llm=self.llm, verbose=self.verbose,
            emission_index=emission,
        )

        # Translate into duel workspace
        duel_dir = project_dir / "duel" / "ava"
        duel_dir.mkdir(parents=True, exist_ok=True)

        try:
            # Reset type status for fresh translation
            type_bp.status = "pending"
            file_path, tokens, refs = translator.translate_type(
                type_bp, module_bp, duel_dir
            )

            code = (duel_dir / file_path).read_text()
            result.code = code
            result.loc = len(code.splitlines())
            result.method_count = _count_methods(code)
            result.tokens_used = tokens
            result.refs_used = len(refs)
            result.code_hash = hashlib.sha256(code.encode()).hexdigest()[:16]
            self.guard.record_tokens(tokens)

            # Density
            from .density import DensityAnalyzer
            analyzer = DensityAnalyzer(duel_dir)
            score = analyzer.analyze_file(type_bp, module_bp)
            result.density = score.density

            # TSC
            from .evaluation import _check_tsc
            from .translator import to_kebab_case
            tsc_path = duel_dir / f"src/{module_bp.name}/{to_kebab_case(type_bp.name)}.ts"
            result.tsc_errors = _check_tsc(tsc_path)

            print(f"    {result.loc} LOC, {result.method_count} methods, "
                  f"density={result.density:.0%}, tsc={result.tsc_errors}, "
                  f"{tokens} tokens")

        except Exception as e:
            print(f"    FAILED: {e}")
            result.tsc_errors = -1

        result.elapsed_s = time.time() - t0
        return result

    # ── Agent B: Claude Raw ─────────────────────────────────

    def _run_claude_raw(self, type_name: str, module: str,
                        module_bp, project_dir: Path,
                        references: list[str],
                        goal: str) -> DuelResult:
        """Run type through raw Claude prompt (no Ava pipeline)."""
        t0 = time.time()
        result = DuelResult(
            agent="claude", type_name=type_name, module=module
        )

        # Build a simple, direct prompt (what a human would write)
        spec = self._build_raw_spec(type_name, module_bp)
        ref_context = self._load_raw_references(type_name, references)

        system = (
            "You are an expert TypeScript developer. Write a complete, "
            "production-quality TypeScript class based on the specification. "
            "Output ONLY the TypeScript code, no explanations.\n"
            "Use strict typing, handle edge cases, and follow best practices."
        )

        user = f"# Task\nImplement the `{type_name}` class for a {goal or module} module.\n\n"
        user += f"# Specification\n{spec}\n"
        if ref_context:
            user += f"\n# Reference (from existing projects)\n{ref_context[:3000]}\n"
        user += (
            "\n# Requirements\n"
            "- Complete implementation with all methods\n"
            "- Strict TypeScript, no `any` types\n"
            "- Export the class\n"
            "- Include necessary imports\n"
        )

        self.guard.throttle()
        resp = self.llm.complete_with_usage(
            [LLMMessage("system", system), LLMMessage("user", user)],
            temperature=0.3,
            max_tokens=6000,
        )

        tokens = resp.usage.total_tokens if resp.usage else 0
        self.guard.record_tokens(tokens)
        result.tokens_used = tokens

        # Clean output
        code = resp.content.strip()
        if code.startswith("```"):
            lines = code.split("\n")
            code = "\n".join(l for l in lines
                             if not l.startswith("```"))

        result.code = code
        result.loc = len(code.splitlines())
        result.method_count = _count_methods(code)
        result.code_hash = hashlib.sha256(code.encode()).hexdigest()[:16]

        # Write to duel workspace
        from .translator import to_kebab_case
        duel_dir = project_dir / "duel" / "claude"
        duel_dir.mkdir(parents=True, exist_ok=True)
        target_file = f"src/{module}/{to_kebab_case(type_name)}.ts"
        full_path = duel_dir / target_file
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(code + "\n")

        # Density (same blueprint, Claude's code)
        type_bp = None
        for t in module_bp.types:
            if t.name == type_name:
                type_bp = t
                break

        if type_bp:
            from .density import DensityAnalyzer
            analyzer = DensityAnalyzer(duel_dir)
            score = analyzer.analyze_file(type_bp, module_bp)
            result.density = score.density

        # TSC
        from .evaluation import _check_tsc
        result.tsc_errors = _check_tsc(full_path)

        print(f"    {result.loc} LOC, {result.method_count} methods, "
              f"density={result.density:.0%}, tsc={result.tsc_errors}, "
              f"{tokens} tokens")

        result.elapsed_s = time.time() - t0
        return result

    # ── Helpers ─────────────────────────────────────────────

    def _build_raw_spec(self, type_name: str, module_bp) -> str:
        """Build a human-readable spec from blueprint (for Claude raw)."""
        for t in module_bp.types:
            if t.name == type_name:
                lines = [f"Class: {t.name} ({t.kind})"]
                if t.fields:
                    field_names = [f.name if hasattr(f, 'name') else str(f)
                                   for f in t.fields]
                    lines.append(f"Fields: {', '.join(field_names)}")
                if t.methods:
                    method_names = [m.name if hasattr(m, 'name') else str(m)
                                    for m in t.methods]
                    lines.append(f"Methods: {', '.join(method_names)}")
                if t.static_members:
                    static_names = [m.name if hasattr(m, 'name') else str(m)
                                    for m in t.static_members]
                    lines.append(f"Static: {', '.join(static_names)}")
                if t.constraints:
                    c_strs = [str(c) for c in t.constraints]
                    lines.append(f"Constraints: {'; '.join(c_strs)}")
                return "\n".join(lines)
        return f"Implement {type_name} class"

    def _load_raw_references(self, type_name: str,
                             references: list[str]) -> str:
        """Load raw reference descriptor for a type (no emission scoring)."""
        import yaml
        for project in references:
            project_dir = self.out_dir / project
            if not project_dir.is_dir():
                continue
            for yaml_path in project_dir.rglob("*.yaml"):
                if yaml_path.name in ("workspace.yaml", "deps.yaml", "meta.yaml"):
                    continue
                try:
                    text = yaml_path.read_text()
                    lines = [l for l in text.split("\n") if not l.startswith("##")]
                    data = yaml.safe_load("\n".join(lines))
                    if not data:
                        continue
                    for td in data.get("types", []):
                        if isinstance(td, dict) and td.get("name") == type_name:
                            return text
                except Exception:
                    continue
        return ""

    def _get_or_create_blueprint(self, target: str, references: list[str],
                                 module: str, types: list[str],
                                 goal: str, emission) -> Optional:
        """Load existing blueprint or create a minimal one."""
        from .blueprint import ModuleBlueprint, TypeBlueprint, FieldSpec, MethodSpec

        # Try loading existing
        bp_path = self.projects_dir / target / "blueprints" / f"{module}.bp.yaml"
        if bp_path.exists():
            try:
                module_bp = ModuleBlueprint.load(bp_path)
                self._log(f"loaded existing blueprint: {len(module_bp.types)} types")
                return module_bp
            except Exception:
                pass

        # Create from reference descriptors
        self._log("creating blueprint from references...")
        import yaml

        found_types = []
        for project in references:
            project_dir = self.out_dir / project
            if not project_dir.is_dir():
                continue
            for yaml_path in project_dir.rglob("*.yaml"):
                if yaml_path.name in ("workspace.yaml", "deps.yaml", "meta.yaml"):
                    continue
                try:
                    text = yaml_path.read_text()
                    lines = [l for l in text.split("\n") if not l.startswith("##")]
                    data = yaml.safe_load("\n".join(lines))
                    if not data:
                        continue
                    for td in data.get("types", []):
                        if not isinstance(td, dict):
                            continue
                        name = td.get("name", "")
                        if name in types:
                            # Convert to TypeBlueprint
                            methods = []
                            for key in ("methods", "static_methods"):
                                for m in td.get(key, []):
                                    mname = m if isinstance(m, str) else m.get("name", "")
                                    if mname:
                                        methods.append(MethodSpec(name=mname))

                            fields = []
                            for f in td.get("fields", []):
                                fname = f if isinstance(f, str) else f.get("name", "")
                                if fname:
                                    fields.append(FieldSpec(name=fname))

                            from .translator import to_kebab_case
                            type_bp = TypeBlueprint(
                                name=name,
                                kind=td.get("kind", "class"),
                                target_file=f"src/{module}/{to_kebab_case(name)}.ts",
                                fields=fields,
                                methods=methods,
                                references=[f"{project}/{yaml_path.relative_to(project_dir)}"],
                            )
                            found_types.append(type_bp)
                except Exception:
                    continue

        if not found_types:
            self._log("no types found in references!")
            return None

        module_bp = ModuleBlueprint(
            name=module,
            language="typescript",
            target_dir=f"src/{module}",
            types=found_types,
        )

        # Save blueprint
        bp_path.parent.mkdir(parents=True, exist_ok=True)
        module_bp.save(bp_path)
        self._log(f"created blueprint with {len(found_types)} types")

        return module_bp

    # ── Output ──────────────────────────────────────────────

    def _print_round(self, round_: DuelRound):
        """Print comparison for one round."""
        W = 70
        a = round_.ava
        c = round_.claude

        if not a or not c:
            return

        print(f"\n  {'─' * (W - 4)}")
        print(f"  {'Metric':<20} {'AVA':>15} {'CLAUDE':>15} {'Winner':>12}")
        print(f"  {'─' * (W - 4)}")

        # LOC (less is better for same functionality)
        loc_w = "AVA" if a.loc <= c.loc else "CLAUDE"
        print(f"  {'LOC':<20} {a.loc:>15} {c.loc:>15} {loc_w:>12}")

        # Methods
        meth_w = "AVA" if a.method_count >= c.method_count else "CLAUDE"
        print(f"  {'Methods':<20} {a.method_count:>15} {c.method_count:>15} {meth_w:>12}")

        # Density (higher is better)
        dens_a = f"{a.density:.0%}"
        dens_c = f"{c.density:.0%}"
        dens_w = "AVA" if a.density >= c.density else "CLAUDE"
        print(f"  {'Density':<20} {dens_a:>15} {dens_c:>15} {dens_w:>12}")

        # TSC errors (lower is better)
        tsc_a = str(a.tsc_errors) if a.tsc_errors >= 0 else "N/A"
        tsc_c = str(c.tsc_errors) if c.tsc_errors >= 0 else "N/A"
        if a.tsc_errors >= 0 and c.tsc_errors >= 0:
            tsc_w = "AVA" if a.tsc_errors <= c.tsc_errors else "CLAUDE"
        else:
            tsc_w = "—"
        print(f"  {'TSC Errors':<20} {tsc_a:>15} {tsc_c:>15} {tsc_w:>12}")

        # Tokens (lower is better)
        tok_w = "AVA" if a.tokens_used <= c.tokens_used else "CLAUDE"
        print(f"  {'Tokens':<20} {a.tokens_used:>15,} {c.tokens_used:>15,} {tok_w:>12}")

        # Refs used
        print(f"  {'Refs Used':<20} {a.refs_used:>15} {c.refs_used:>15} {'—':>12}")

        # Time
        time_w = "AVA" if a.elapsed_s <= c.elapsed_s else "CLAUDE"
        time_a = f"{a.elapsed_s:.1f}s"
        time_c = f"{c.elapsed_s:.1f}s"
        print(f"  {'Time':<20} {time_a:>15} {time_c:>15} {time_w:>12}")

        print(f"  {'─' * (W - 4)}")

    def _print_final_report(self, report: DuelReport):
        """Print aggregate duel report."""
        W = 70
        print(f"\n{'━' * W}")
        print(f"  DUEL REPORT: {report.target}")
        print(f"{'━' * W}")

        # Aggregate wins
        ava_wins = 0
        claude_wins = 0

        for r in report.rounds:
            if not r.ava or not r.claude:
                continue

            # Score: density (40%), methods (20%), LOC efficiency (20%), TSC (20%)
            ava_score = 0.0
            claude_score = 0.0

            # Density
            if r.ava.density > r.claude.density:
                ava_score += 40
            elif r.claude.density > r.ava.density:
                claude_score += 40
            else:
                ava_score += 20
                claude_score += 20

            # Methods (more = better)
            if r.ava.method_count > r.claude.method_count:
                ava_score += 20
            elif r.claude.method_count > r.ava.method_count:
                claude_score += 20
            else:
                ava_score += 10
                claude_score += 10

            # LOC (less = better for similar functionality)
            if r.ava.loc < r.claude.loc:
                ava_score += 20
            elif r.claude.loc < r.ava.loc:
                claude_score += 20
            else:
                ava_score += 10
                claude_score += 10

            # TSC (fewer errors = better)
            a_tsc = r.ava.tsc_errors if r.ava.tsc_errors >= 0 else 999
            c_tsc = r.claude.tsc_errors if r.claude.tsc_errors >= 0 else 999
            if a_tsc < c_tsc:
                ava_score += 20
            elif c_tsc < a_tsc:
                claude_score += 20
            else:
                ava_score += 10
                claude_score += 10

            winner = "AVA" if ava_score > claude_score else (
                "CLAUDE" if claude_score > ava_score else "TIE")

            if winner == "AVA":
                ava_wins += 1
            elif winner == "CLAUDE":
                claude_wins += 1

            icon = {"AVA": "A", "CLAUDE": "C", "TIE": "="}.get(winner, "?")
            print(f"  [{icon}] {r.type_name}: AVA {ava_score:.0f} vs CLAUDE {claude_score:.0f}")

        total = len(report.rounds)
        ties = total - ava_wins - claude_wins

        print(f"\n  {'─' * (W - 4)}")
        print(f"  FINAL SCORE:")
        print(f"    AVA:    {ava_wins}/{total} wins")
        print(f"    CLAUDE: {claude_wins}/{total} wins")
        if ties:
            print(f"    TIES:   {ties}/{total}")

        overall = "AVA" if ava_wins > claude_wins else (
            "CLAUDE" if claude_wins > ava_wins else "TIE")
        print(f"\n  WINNER: {overall}")
        print(f"  Tokens: {report.total_tokens:,}  Time: {report.elapsed_s:.1f}s")
        print(f"{'━' * W}")

    def _save_results(self, target: str, report: DuelReport):
        """Save duel results to JSON."""
        project_dir = self.projects_dir / target
        results = {
            "target": report.target,
            "references": report.references,
            "total_tokens": report.total_tokens,
            "elapsed_s": report.elapsed_s,
            "rounds": [],
        }
        for r in report.rounds:
            round_data = {"type": r.type_name, "module": r.module}
            for agent_name, res in [("ava", r.ava), ("claude", r.claude)]:
                if res:
                    round_data[agent_name] = {
                        "loc": res.loc,
                        "method_count": res.method_count,
                        "density": round(res.density, 3),
                        "tsc_errors": res.tsc_errors,
                        "tokens_used": res.tokens_used,
                        "elapsed_s": round(res.elapsed_s, 2),
                        "refs_used": res.refs_used,
                        "code_hash": res.code_hash,
                    }
            results["rounds"].append(round_data)

        out_path = project_dir / "duel-results.json"
        out_path.write_text(json.dumps(results, indent=2) + "\n")
        self._log(f"saved results → {out_path}")


def _count_methods(code: str) -> int:
    """Count methods/functions in TypeScript code."""
    import re
    pattern = re.compile(
        r'(?:public|private|protected|static|async|get|set)\s+(\w+)\s*\('
        r'|(\w+)\s*\([^)]*\)\s*[:{]'
    )
    keywords = {"if", "for", "while", "switch", "catch", "return", "new",
                "throw", "console", "super", "import", "from", "require"}
    count = 0
    for match in pattern.finditer(code):
        name = match.group(1) or match.group(2)
        if name and name not in keywords:
            count += 1
    return count
